# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dldetection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64ldetection.proto\x12\taiservice\")\n\tDlRequest\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0e\n\x06imdata\x18\x02 \x01(\x0c\"<\n\x0e\x44lBoundingRect\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01w\x18\x03 \x01(\x05\x12\t\n\x01h\x18\x04 \x01(\x05\"\x1f\n\x07\x44lPoint\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\",\n\x06\x44lMask\x12\"\n\x06points\x18\x01 \x03(\x0b\x32\x12.aiservice.DlPoint\"t\n\x08\x44lResult\x12\x0f\n\x07\x63lassid\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\'\n\x04rect\x18\x03 \x01(\x0b\x32\x19.aiservice.DlBoundingRect\x12\x1f\n\x04mask\x18\x04 \x01(\x0b\x32\x11.aiservice.DlMask\"2\n\nDlResponse\x12$\n\x07results\x18\x01 \x03(\x0b\x32\x13.aiservice.DlResult2I\n\tAiService\x12<\n\x0b\x44lDetection\x12\x14.aiservice.DlRequest\x1a\x15.aiservice.DlResponse\"\x00\x62\x06proto3')



_DLREQUEST = DESCRIPTOR.message_types_by_name['DlRequest']
_DLBOUNDINGRECT = DESCRIPTOR.message_types_by_name['DlBoundingRect']
_DLPOINT = DESCRIPTOR.message_types_by_name['DlPoint']
_DLMASK = DESCRIPTOR.message_types_by_name['DlMask']
_DLRESULT = DESCRIPTOR.message_types_by_name['DlResult']
_DLRESPONSE = DESCRIPTOR.message_types_by_name['DlResponse']
DlRequest = _reflection.GeneratedProtocolMessageType('DlRequest', (_message.Message,), {
  'DESCRIPTOR' : _DLREQUEST,
  '__module__' : 'dldetection_pb2'
  # @@protoc_insertion_point(class_scope:aiservice.DlRequest)
  })
_sym_db.RegisterMessage(DlRequest)

DlBoundingRect = _reflection.GeneratedProtocolMessageType('DlBoundingRect', (_message.Message,), {
  'DESCRIPTOR' : _DLBOUNDINGRECT,
  '__module__' : 'dldetection_pb2'
  # @@protoc_insertion_point(class_scope:aiservice.DlBoundingRect)
  })
_sym_db.RegisterMessage(DlBoundingRect)

DlPoint = _reflection.GeneratedProtocolMessageType('DlPoint', (_message.Message,), {
  'DESCRIPTOR' : _DLPOINT,
  '__module__' : 'dldetection_pb2'
  # @@protoc_insertion_point(class_scope:aiservice.DlPoint)
  })
_sym_db.RegisterMessage(DlPoint)

DlMask = _reflection.GeneratedProtocolMessageType('DlMask', (_message.Message,), {
  'DESCRIPTOR' : _DLMASK,
  '__module__' : 'dldetection_pb2'
  # @@protoc_insertion_point(class_scope:aiservice.DlMask)
  })
_sym_db.RegisterMessage(DlMask)

DlResult = _reflection.GeneratedProtocolMessageType('DlResult', (_message.Message,), {
  'DESCRIPTOR' : _DLRESULT,
  '__module__' : 'dldetection_pb2'
  # @@protoc_insertion_point(class_scope:aiservice.DlResult)
  })
_sym_db.RegisterMessage(DlResult)

DlResponse = _reflection.GeneratedProtocolMessageType('DlResponse', (_message.Message,), {
  'DESCRIPTOR' : _DLRESPONSE,
  '__module__' : 'dldetection_pb2'
  # @@protoc_insertion_point(class_scope:aiservice.DlResponse)
  })
_sym_db.RegisterMessage(DlResponse)

_AISERVICE = DESCRIPTOR.services_by_name['AiService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DLREQUEST._serialized_start=32
  _DLREQUEST._serialized_end=73
  _DLBOUNDINGRECT._serialized_start=75
  _DLBOUNDINGRECT._serialized_end=135
  _DLPOINT._serialized_start=137
  _DLPOINT._serialized_end=168
  _DLMASK._serialized_start=170
  _DLMASK._serialized_end=214
  _DLRESULT._serialized_start=216
  _DLRESULT._serialized_end=332
  _DLRESPONSE._serialized_start=334
  _DLRESPONSE._serialized_end=384
  _AISERVICE._serialized_start=386
  _AISERVICE._serialized_end=459
# @@protoc_insertion_point(module_scope)
